[Application][Domain][WIB-1] Customer commented an order feature
Sylius/SyliusOrderCommentsPlugin pull request #1
Opened 2017-07-25 09:15 UTC by Arminek

2017-07-25 09:48 UTC, lchrusciel requested changes

2017-07-25 09:48 UTC, lchrusciel commented on features/administrator_checks_an_commented_order.feature
> +    In order to check unread customer's comments
In order to increase UX of my shop

2017-07-25 09:48 UTC, lchrusciel commented on features/customer_commented_an_order.feature
> +    In order to provide ability to comment an order
In order to discuss further order details after placing an order

2017-07-25 09:48 UTC, lchrusciel commented on features/customer_commented_an_order.feature
> +Feature: Adding comments to order
I think file names should correspond to feature headline

2017-07-25 09:51 UTC, Arminek commented on features/administrator_checks_an_commented_order.feature
> +    In order to check unread customer's comments
Hmm I think is too general. Almost all new features can improve UX of the store 💃

2017-07-25 09:53 UTC, Arminek commented on features/customer_commented_an_order.feature
> +Feature: Adding comments to order
So maybe I will change the headline? `Customer commented an order?` or `Commenting an order by a customer`? WDYT?

2017-07-25 09:53 UTC, Arminek commented on features/customer_commented_an_order.feature
> +    In order to provide ability to comment an order
👍

2017-07-25 12:37 UTC, CoderMaggie submitted a review, later dismissed

2017-07-25 12:37 UTC, CoderMaggie commented on features/administrator_checks_an_commented_order.feature
> +    In order to check unread customer's comments
`In order to make the process of ordering my goods better`

2017-07-25 12:37 UTC, CoderMaggie commented on features/administrator_checks_an_commented_order.feature
> +    I want to be able to communicate with my customers
`I want to be able to communicate with my customers via order comments`

2017-07-25 12:37 UTC, CoderMaggie commented on features/administrator_checks_an_commented_order.feature
> +        Given a customer commented an order "#00000022" with "Hello"
the order ;)

2017-07-25 12:37 UTC, CoderMaggie commented on features/customer_commented_an_order.feature
> +Feature: Adding comments to order
`Commenting an order by a customer` is great.

2017-07-25 12:37 UTC, CoderMaggie commented on features/customer_commented_an_order.feature
> +    I want to be able to communicate with the store owner
via order comments

2017-07-27 07:31 UTC, CoderMaggie commented on features/administrator_checks_an_commented_order.feature
> +    In order to check unread customer's comments
`In order to let customers communicate with the administrators and solve problems in their orders`

2017-07-27 07:41 UTC, lchrusciel requested changes

2017-07-27 07:41 UTC, lchrusciel commented on features/administrator_checks_an_commented_order.feature
> +    In order to check unread customer's comments
Still not updated

2017-07-27 07:41 UTC, lchrusciel commented on features/commenting_an_order_by_a_customer.feature
> +        When I try to comment an not existing order with "Hello"
*a* not existing

2017-07-27 07:41 UTC, lchrusciel commented on src/Resources/config/doctrine/model/Comment.orm.xml
> +    <mapped-superclass name="Sylius\OrderCommentsPlugin\Domain\Model\Comment" table="sylius_order_comment">
As this class is final we should use an `entity` instead of `mapped-superclass`

2017-07-27 07:41 UTC, lchrusciel commented on features/commenting_an_order_by_a_customer.feature
> +        When I try to comment an order "#00000022" with empty message
with *an* empty message

2017-07-27 07:41 UTC, lchrusciel commented on tests/Behat/Context/Application/OrderCommentsContext.php
> +     * @Then /^(this order) should have comment with "([^"]+)" from this customer$/
have *a* comment

2017-07-27 07:41 UTC, lchrusciel commented on tests/Behat/Context/Application/OrderCommentsContext.php
> +            $comment->message() !== $message &&
Should we use `or` instead of `and` here?

2017-07-27 07:41 UTC, lchrusciel commented on tests/Behat/Context/Application/OrderCommentsContext.php
> +            throw $this->sharedStorage->get('exception');
o.O

2017-07-27 07:41 UTC, lchrusciel commented on tests/Behat/Context/Domain/OrderCommentsContext.php
> +        $user = $this->sharedStorage->get('user');
Can't we extract this line to some transformer and map it to `I`, so the user would be passed as an argument? Is it done already?

2017-07-27 07:41 UTC, lchrusciel commented on tests/Behat/Context/Domain/OrderCommentsContext.php
> +            $comment->authorEmail() != $user->getEmail() &&
`!=` -> `!==`

2017-07-27 07:41 UTC, lchrusciel commented on tests/Behat/Context/Domain/OrderCommentsContext.php
> +            $comment->message() !== $message &&
`&&` -> `||`

2017-07-27 07:41 UTC, lchrusciel commented on tests/Behat/Resources/services.xml
> +        <service id="sylius.behat.domain.order_comments" class="Tests\Sylius\OrderCommentsPlugin\Behat\Context\Domain\OrderCommentsContext">
`sylius` -> `order_comment_plugin`/`sylius_order_comment_plugin`?

2017-07-27 07:41 UTC, lchrusciel commented on tests/Behat/Resources/suites.yml
> +        domain_order_comments:
Later we should think of splitting this file, and place an order_comment suite inside a domain and application folder. IT can happen, that one would like to use only our domain but provide own application implementation

2017-07-27 07:41 UTC, lchrusciel commented on tests/Comments/Domain/Model/CommentTest.php
> +    public function it_cannot_be_created_with_invalid_author_email(): void
I would combine both tests

2017-07-27 07:41 UTC, lchrusciel commented on src/Domain/Model/Email.php
> +    public function __toString(): string
Is this method added only for test purposes?

2017-07-27 07:41 UTC, lchrusciel commented on tests/Comments/Domain/Model/CommentTest.php
> +        $this->assertEquals('test@test.com', $comment->authorEmail());
`new Email('test@test.com')`?

2017-07-27 07:46 UTC, Arminek commented on tests/Behat/Context/Domain/OrderCommentsContext.php
> +            $comment->authorEmail() != $user->getEmail() &&
I want to compare only values cuz author email is an `Email` object.

2017-07-27 07:47 UTC, Arminek commented on src/Domain/Model/Email.php
> +    public function __toString(): string
Nope xD

2017-07-27 09:21 UTC, lchrusciel approved these changes

2017-07-27 09:21 UTC, merged