[Feature] [Domain] Describe adding comment by admin
Sylius/SyliusOrderCommentsPlugin pull request #8
Opened 2017-07-27 11:58 UTC by lchrusciel

2017-07-28 07:09 UTC, CoderMaggie requested changes

2017-07-28 07:09 UTC, CoderMaggie commented on features/commenting_an_order_by_an_administrator.feature
> +    In order to respond to the customers comment
`In order to communicate with the customer that made an order`

2017-07-28 07:09 UTC, CoderMaggie commented on features/commenting_an_order_by_an_administrator.feature
> +        When I comment an order "#00000022" with "How can I help you?"
the order

2017-07-28 07:09 UTC, CoderMaggie commented on features/commenting_an_order_by_an_administrator.feature
> +        Then this order should have a comment with "How can I help you?" from this customer
customer? ;>

2017-07-28 07:09 UTC, CoderMaggie commented on features/commenting_an_order_by_an_administrator.feature
> +        Then this order should not have empty comment from this customer
`Then this order should not have any comments`
`And I should be notified that a message is required`

2017-07-28 07:09 UTC, CoderMaggie commented on features/commenting_an_order_by_an_administrator.feature
> +    Scenario: Administrator cannot comment an order which does not exist
This is the weirdest scenario I've seen. How can you even try commenting an order that does not exist? You cannot go to order show of a not existing order xD

2017-07-28 07:09 UTC, CoderMaggie commented on features/commenting_an_order_by_an_administrator.feature
> +    Scenario: Sending the email notification to the customer about unread administrator's comments
an email notification
about unread <del>administrator's</del> comments

2017-07-28 07:09 UTC, CoderMaggie commented on features/commenting_an_order_by_an_administrator.feature
> +        Then the notification email should be sent to the administrator
to the customer ;>

2017-07-31 12:29 UTC, CoderMaggie commented on tests/Comments/Domain/Model/CommentTest.php
> +    public function customer_comment_cannot_be_created_with_invalid_rmail(): void
rmail!

2017-07-31 12:29 UTC, CoderMaggie commented on tests/Behat/Context/Domain/AdministratorOrderCommentsContext.php
> +    public function thisOrderShouldNotHaveEmptyCommentFromThisCustomer(): void
the function name should also change I suppose ;>

2017-07-31 12:29 UTC, CoderMaggie commented on tests/Behat/Context/Domain/AdministratorOrderCommentsContext.php
> +    public function aCustomerTryToCommentsTheOrderWithEmptyMessage(OrderInterface $order): void
`aCustomerTriesToCommentTheOrderWithEmptyMessage`

2017-07-31 12:41 UTC, Arminek commented on src/Domain/Model/Comment.php
> +    public static function orderByAdministrator(OrderInterface $order, string $customerEmail, string $message): self
`$customerEmail` -> `$administratorEmail`

2017-07-31 12:42 UTC, CoderMaggie approved these changes

2017-07-31 13:00 UTC, merged